version: '3.9'

x-base_service: &base_service

  volumes:
    # prod
    - &v_prod /mnt/hdd0/prj/finance-fastapi/prod:/data
    # dev
    - &v_dev /mnt/hdd0/prj/finance-fastapi/dev:/data
    - &v_src .:/api
  environment:
    - TZ='Asia/Seoul'
  stop_signal: SIGKILL
  tty: true

name: finace-fastapi

services:
  
  prod:
    <<: *base_service
    ports:
      - "${PROD_PORT:-8080}:8080"
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    volumes:
      - *v_prod

  dev:
    <<: *base_service
    ports:
      - "${DEV_PORT:-8081}:8080"
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - *v_dev
      - *v_src
    command: /bin/bash
